# S02 T02: Estructura d'una Matriu
## Nivell 1
Treballem els conceptes de l'estructura d'una matriu, dimensió, eixos i la vectorització que ens permet reduir l'ús de for loops en operacions aritmètiques o matemàtiques..

### Exercici 1
Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu. 

In [22]:
import numpy as np
#Array de 1D amb 8 nombres
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("La dimensió del array és:", arr.ndim) 
print("La forma del array és :", arr.shape)

La dimensió del array és: 1
La forma del array és : (8,)


### Exercici 2

De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts.

In [15]:
mitjana = np.average(arr)
print("La mitjana de la matriu és:", mitjana)

La mitjana de la matriu és: 4.5


### Exercici 3

Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [34]:
#Importem random per generar una matriu aleatoria
from numpy import random
matriu5 = random.randint(10, size=(5,5))
print(matriu5)

#Valor màxim de la matriu
print(np.max(matriu5))

#Valor màxim de la matriu per cada eix
print("El valor màxim de cada coumna és:", np.max(matriu5, axis=0))
print("El valor màxim de cada fila és:", np.max(matriu5, axis=1))


[[3 6 3 0 7]
 [6 7 0 5 8]
 [2 5 5 4 0]
 [0 4 5 4 4]
 [8 0 9 3 9]]
9
El valor màxim de cada coumna és: [8 7 9 5 9]
El valor màxim de cada fila és: [7 8 5 5 9]


## Nivell 2

Treballem els conceptes de l'estructura d'una matriu, Broadcasting, indexació, Mask...

### Exercici 4

Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".