# S02 T02: Estructura d'una Matriu
## Nivell 1
Treballem els conceptes de l'estructura d'una matriu, dimensió, eixos i la vectorització que ens permet reduir l'ús de for loops en operacions aritmètiques o matemàtiques..

### Exercici 1
Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu. 

In [ ]:
import numpy as np
#Array de 1D amb 8 nombres
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("La dimensió del array és:", arr.ndim) 
print("La forma del array és :", arr.shape)

La dimensió del array és: 1
La forma del array és : (8,)


### Exercici 2

De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts.

In [ ]:
mitjana = np.average(arr)
print("La mitjana de la matriu és:", mitjana)

La mitjana de la matriu és: 4.5


### Exercici 3

Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [ ]:
#Importem random per generar una matriu aleatòria
from numpy import random
matriu5 = random.randint(10, size=(5,5))
print(matriu5)

#Valor màxim de la matriu
print("El valor màxim de tota la matriu és:", np.max(matriu5))

#Valor màxim de la matriu per cada eix
print("El valor màxim de cada columna és:", np.max(matriu5, axis=0))
print("El valor màxim de cada fila és:", np.max(matriu5, axis=1))

[[1 2 8 0 8]
 [1 0 2 9 1]
 [5 2 8 3 2]
 [9 5 2 3 2]
 [4 0 2 8 0]]
El valor màxim de tota la matriu és: 9
El valor màxim de cada columna és: [9 5 8 9 8]
El valor màxim de cada fila és: [8 9 8 9 8]


## Nivell 2

Treballem els conceptes de l'estructura d'una matriu, Broadcasting, indexació, Mask...

### Exercici 4

Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".

In [7]:
#Les regles de Broadcasting a Numpy es poden trobar a https://numpy.org/doc/stable/user/basics.broadcasting.html
#Exemple de dos matrius de les mateixes dimensions
import numpy
from numpy import random
matriu31 = random.randint(10, size=(3,3))
matriu32 = random.randint(10, size=(3,3))
print("Primera matriu 2D de 3x3:\n", matriu31)
print("Segona matriu 2D de 3x3:\n", matriu32)
novamatriu = matriu31 * matriu32
print("La multiplicació de les dues matrius és:\n", novamatriu)
matriu41 = random.randint(10, size=(3,3))
print("Matriu 2D de 4x4:\n", matriu41)
matriu1 = numpy.array([2])
print("Matriu de mida 1:\n", matriu1)
print("La multiplicació de la matriu 2D per la de mida 1 és:\n", matriu41 * matriu1)

Primera matriu 2D de 3x3:
 [[4 0 4]
 [9 7 4]
 [1 4 8]]
Segona matriu 2D de 3x3:
 [[9 4 3]
 [2 9 7]
 [9 5 2]]
La multiplicació de les dues matrius és:
 [[36  0 12]
 [18 63 28]
 [ 9 20 16]]
Matriu 2D de 4x4:
 [[5 4 2]
 [4 4 7]
 [7 0 4]]
Matriu de mida 1:
 [2]
La multiplicació de la matriu 2D per la de mida 1 és:
 [[10  8  4]
 [ 8  8 14]
 [14  0  8]]


### Exercici 5

Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.

In [24]:
import numpy
from numpy import random
matriu33 = random.randint(10, size=(3,3))
print("Primer creem una matriu:\n", matriu33)
fila = matriu33[0]
print("Extreiem la primera fila:", fila)
columna = matriu33[:,1]
print("Extreiem la segona columna:", columna)
print("La suma dels seus valors és:", fila + columna)

Primer creem una matriu:
 [[5 8 4]
 [2 2 0]
 [1 3 3]]
Extreiem la primera fila: [5 8 4]
Extreiem la segona columna: [8 2 3]
La suma dels seus valors és:  [13 10  7]


### Exercici 6

Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre.

Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.

In [ ]:
import numpy as np
import numpy.ma as ma
from numpy import random
