# S02 T02: Estructura d'una Matriu
## Nivell 1
Treballem els conceptes de l'estructura d'una matriu, dimensió, eixos i la vectorització que ens permet reduir l'ús de for loops en operacions aritmètiques o matemàtiques..


### Exercici 1
Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu. 

In [ ]:
import numpy as np
#Array de 1D amb 8 nombres
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("La dimensió del array és:", arr.ndim) 
print("La forma del array és :", arr.shape)

La dimensió del array és: 1
La forma del array és : (8,)


### Exercici 2

De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts.

In [ ]:
mitjana = np.average(arr)
print("La mitjana de la matriu és:", mitjana)

La mitjana de la matriu és: 4.5


### Exercici 3

Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [ ]:
#Importem random per generar una matriu aleatòria

matriu5 = random.randint(10, size=(5,5))
print(matriu5)

#Valor màxim de la matriu
print("El valor màxim de tota la matriu és:", np.max(matriu5))

#Valor màxim de la matriu per cada eix
print("El valor màxim de cada columna és:", np.max(matriu5, axis=0))
print("El valor màxim de cada fila és:", np.max(matriu5, axis=1))

[[7 7 0 6 1]
 [6 4 3 6 2]
 [9 7 2 2 0]
 [3 0 9 1 5]
 [1 7 9 7 3]]
El valor màxim de tota la matriu és: 9
El valor màxim de cada columna és: [9 7 9 7 5]
El valor màxim de cada fila és: [7 6 9 9 9]


## Nivell 2

Treballem els conceptes de l'estructura d'una matriu, Broadcasting, indexació, Mask...

### Exercici 4

Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".

In [ ]:
#Les regles de Broadcasting a Numpy es poden trobar a https://numpy.org/doc/stable/user/basics.broadcasting.html
#Exemple de dos matrius de les mateixes dimensions
matriu31 = random.randint(10, size=(3,3))
matriu32 = random.randint(10, size=(3,3))
print("Primera matriu 2D de 3x3:\n", matriu31)
print("Segona matriu 2D de 3x3:\n", matriu32)
novamatriu = matriu31 * matriu32
print("La multiplicació de les dues matrius és:\n", novamatriu)
matriu41 = random.randint(10, size=(3,3))
#Exemple de multiplicació amb una matriu de mida 1
print("Matriu 2D de 4x4:\n", matriu41)
matriu1 = np.array([2])
print("Matriu de mida 1:\n", matriu1)
print("La multiplicació de la matriu 2D per la de mida 1 és:\n", matriu41 * matriu1)

Primera matriu 2D de 3x3:
 [[0 4 1]
 [4 0 0]
 [2 3 9]]
Segona matriu 2D de 3x3:
 [[5 6 3]
 [1 8 6]
 [7 2 0]]
La multiplicació de les dues matrius és:
 [[ 0 24  3]
 [ 4  0  0]
 [14  6  0]]
Matriu 2D de 4x4:
 [[7 6 5]
 [5 7 6]
 [1 7 2]]
Matriu de mida 1:
 [2]
La multiplicació de la matriu 2D per la de mida 1 és:
 [[14 12 10]
 [10 14 12]
 [ 2 14  4]]


### Exercici 5

Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.

In [ ]:
matriu33 = random.randint(10, size=(3,3))
print("Primer creem una matriu:\n", matriu33)
fila = matriu33[0]
print("Extreiem la primera fila:", fila)
columna = matriu33[:,1]
print("Extreiem la segona columna:", columna)
print("La suma dels seus valors és:", fila + columna)

Primer creem una matriu:
 [[5 8 4]
 [2 2 0]
 [1 3 3]]
Extreiem la primera fila: [5 8 4]
Extreiem la segona columna: [8 2 3]
La suma dels seus valors és:  [13 10  7]


### Exercici 6

Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre.

Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.

In [ ]:
quartapart = (matriu33%4 == 0)
print("La matriu booleana divida per quatre és:\n", quartapart)

La matriu booleana divida per quatre és:
 [[False  True  True]
 [False False  True]
 [False False False]]


### Exercici 7

A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però encara obteniu les dades que esteu cercant.

In [ ]:
print("Les dades que han retornat True (divisibles per 4) son:", matriu33[quartapart])

Les dades que han retornat True son: [8 4 0]


## Nivell 3

Manipulació d’imatges amb Matplotlib.

Carregareu qualsevol imatge (jpg, png ..) amb Matplotlib. adoneu-vos que les imatges RGB (Red, Green, Blue) són realment només amplades × alçades × 3 matrius (tres canals Vermell, Verd i Blau), una per cada color de nombres enters int8,

manipuleu aquests bytes i torneu a utilitzar Matplotlib per desar la imatge modificada un cop hàgiu acabat.

Ajuda:Importeu, import matplotlib.image as mpimg. estudieu el metodde mpimg.imread(()

### Exercici 8

Mostreu-me a veure que passa quan eliminem el canal G Verd o B Blau.

Mostreu-me a veure què passa quan eliminem el canal G Verd o B Blau. Hauries d'utilitzar la indexació per seleccionar el canal que voleu anul·lar.

Utilitzar el mètode, mpimg.imsave () de la llibreria importada, per guardar les imatges modificades i que haureu de pujar al vostre repositori a github.


In [49]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
img = mpimg.imread('https://stsci-opo.org/STScI-01EVT1KG6QRFHEHHA14GT3FR0G.png')
print(img)

[[[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  ...
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]

 [[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  ...
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]

 [[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  ...
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]

 ...

 [[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  ...
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]

 [[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  ...
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]

 [[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  ...
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]]
